name: Simulate Jira Tickets

on:
  workflow_dispatch:
    inputs:
      sprint_config:
        description: 'Sprint configuration (format: num_sprints,tickets_per_sprint,incomplete_tickets_per_sprint,sprint_length_days)'
        required: true
        default: '2,5,1,14'
        type: string
      ticket_config:
        description: 'Ticket configuration (format: work_chance,block_chance,ticket_types)'
        required: true
        default: '70,30,Story,Task,Bug'
        type: string
      team_config:
        description: 'Team configuration (format: devs,qa,tech_leads,po,sm)'
        required: true
        default: '4,2,1,1,1'
        type: string

jobs:
  simulate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create .env file
        run: |
          # Parse sprint config
          IFS=',' read -r NUM_SPRINTS TICKETS_PER_SPRINT INCOMPLETE_TICKETS SPRINT_LENGTH <<< "${{ inputs.sprint_config }}"
          
          # Parse ticket config
          IFS=',' read -r WORK_CHANCE BLOCK_CHANCE TICKET_TYPES <<< "${{ inputs.ticket_config }}"
          
          # Parse team config
          IFS=',' read -r NUM_DEVS NUM_QA NUM_LEADS NUM_PO NUM_SM <<< "${{ inputs.team_config }}"
          
          echo "JIRA_SERVER=${{ secrets.JIRA_SERVER }}" > .env
          echo "JIRA_EMAIL=${{ secrets.JIRA_EMAIL }}" >> .env
          echo "JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN }}" >> .env
          echo "JIRA_PROJECT_KEY=${{ secrets.JIRA_PROJECT_KEY }}" >> .env
          echo "CLAUDE_API_KEY=${{ secrets.CLAUDE_API_KEY }}" >> .env
          echo "INPUT_NUM_SPRINTS=$NUM_SPRINTS" >> .env
          echo "INPUT_TICKETS_PER_SPRINT=$TICKETS_PER_SPRINT" >> .env
          echo "INPUT_INCOMPLETE_TICKETS_PER_SPRINT=$INCOMPLETE_TICKETS" >> .env
          echo "INPUT_WORK_CHANCE=$WORK_CHANCE" >> .env
          echo "INPUT_BLOCK_CHANCE=$BLOCK_CHANCE" >> .env
          echo "INPUT_SPRINT_LENGTH_DAYS=$SPRINT_LENGTH" >> .env
          echo "INPUT_TICKET_TYPES=$TICKET_TYPES" >> .env
          echo "INPUT_NUM_DEVELOPERS=$NUM_DEVS" >> .env
          echo "INPUT_NUM_QA=$NUM_QA" >> .env
          echo "INPUT_NUM_TECH_LEADS=$NUM_LEADS" >> .env
          echo "INPUT_NUM_PRODUCT_OWNERS=$NUM_PO" >> .env
          echo "INPUT_NUM_SCRUM_MASTERS=$NUM_SM" >> .env
          
      - name: Run simulation
        run: python main.py 